// Generated by scripts/build-web-editor.sh. Edit src/ or root sketch.js, then regenerate.

// ========================================
// src/world/Terrain.js
// ========================================
class Terrain {
    static getProperties(type) {
        const properties = Terrain.TYPES[type];

        if (!properties) {
            throw new Error(`Tipo de terreno inválido: ${type}`);
        }

        return properties;
    }

    static getCost(type) {
        return Terrain.getProperties(type).cost;
    }

    static getSpeedMultiplier(type) {
        return Terrain.getProperties(type).speedMultiplier;
    }

    static isWalkable(type) {
        return Terrain.getProperties(type).walkable;
    }

    static getColor(type) {
        return Terrain.getProperties(type).color;
    }
}

Terrain.SAND = "SAND";
Terrain.MUD = "MUD";
Terrain.WATER = "WATER";
Terrain.OBSTACLE = "OBSTACLE";

Terrain.TYPES = Object.freeze({
    SAND: Object.freeze({
        label: "Areia",
        cost: 10,
        speedMultiplier: 1,
        walkable: true,
        color: Object.freeze([238, 220, 170])
    }),
    MUD: Object.freeze({
        label: "Atoleiro",
        cost: 50,
        speedMultiplier: 0.6,
        walkable: true,
        color: Object.freeze([160, 115, 82])
    }),
    WATER: Object.freeze({
        label: "Água",
        cost: 100,
        speedMultiplier: 0.3,
        walkable: true,
        color: Object.freeze([105, 170, 210])
    }),
    OBSTACLE: Object.freeze({
        label: "Obstáculo",
        cost: Infinity,
        speedMultiplier: 0,
        walkable: false,
        color: Object.freeze([38, 42, 48])
    })
});


// ========================================
// src/world/Cell.js
// ========================================
class Cell {
    constructor(col, row, terrainType = Terrain.SAND) {
        this.position = { col, row };
        this.terrainType = terrainType;
        this.neighbors = [];
    }

    get col() {
        return this.position.col;
    }

    get row() {
        return this.position.row;
    }

    get cost() {
        return Terrain.getCost(this.terrainType);
    }

    get walkable() {
        return Terrain.isWalkable(this.terrainType);
    }

    setTerrain(terrainType) {
        Terrain.getProperties(terrainType);
        this.terrainType = terrainType;
    }

    addNeighbor(cell) {
        if (!this.neighbors.includes(cell)) {
            this.neighbors.push(cell);
        }
    }

    clearNeighbors() {
        this.neighbors = [];
    }

    display(cellSize) {
        const terrainColor = Terrain.getColor(this.terrainType);
        const x = this.col * cellSize;
        const y = this.row * cellSize;

        stroke(180);
        strokeWeight(1);
        fill(...terrainColor);
        rect(x, y, cellSize, cellSize);
    }
}


// ========================================
// src/world/Grid.js
// ========================================
class Grid {
    constructor(cols, rows, cellSize) {
        this.cols = cols;
        this.rows = rows;
        this.cellSize = cellSize;
        this.cells = [];

        this.createCells();
        this.connectNeighbors();
    }

    createCells() {
        for (let row = 0; row < this.rows; row += 1) {
            const currentRow = [];

            for (let col = 0; col < this.cols; col += 1) {
                currentRow.push(new Cell(col, row, Terrain.SAND));
            }

            this.cells.push(currentRow);
        }
    }

    connectNeighbors() {
        const directions = [
            { col: 0, row: -1 },
            { col: 1, row: 0 },
            { col: 0, row: 1 },
            { col: -1, row: 0 }
        ];

        for (let row = 0; row < this.rows; row += 1) {
            for (let col = 0; col < this.cols; col += 1) {
                const cell = this.getCell(col, row);
                cell.clearNeighbors();

                for (const direction of directions) {
                    const neighbor = this.getCell(
                        col + direction.col,
                        row + direction.row
                    );

                    if (neighbor) {
                        cell.addNeighbor(neighbor);
                    }
                }
            }
        }
    }

    getCell(col, row) {
        if (!this.isInside(col, row)) {
            return null;
        }

        return this.cells[row][col];
    }

    isInside(col, row) {
        return col >= 0 && col < this.cols && row >= 0 && row < this.rows;
    }

    getNeighbors(cell) {
        return cell.neighbors.filter((neighbor) => neighbor.walkable);
    }

    getRandomWalkableCell() {
        const walkableCells = this.cells.flat().filter((cell) => cell.walkable);
        // Evita colocar o agente em uma célula isolada, sem espaço para comida.
        const connectedCells = walkableCells.filter((cell) => this.getNeighbors(cell).length > 0);
        const candidates = connectedCells.length > 0 ? connectedCells : walkableCells;

        return candidates[Math.floor(Math.random() * candidates.length)] || null;
    }

    setTerrain(col, row, terrainType) {
        const cell = this.getCell(col, row);

        if (!cell) {
            return false;
        }

        cell.setTerrain(terrainType);
        return true;
    }

    generateProcedural(options = {}) {
        const obstacleChance = options.obstacleChance === undefined || options.obstacleChance === null
            ? 0.15 : options.obstacleChance;
        const noiseScale = options.noiseScale === undefined || options.noiseScale === null
            ? 0.10 : options.noiseScale;
        // As opções antigas continuam aceitas como limites/faixas do campo de ruído.
        const waterThreshold = options.waterThreshold === undefined || options.waterThreshold === null
            ? (options.waterChance === undefined || options.waterChance === null
                ? 0.32 : options.waterChance) : options.waterThreshold;
        const mudThreshold = options.mudThreshold === undefined || options.mudThreshold === null
            ? waterThreshold + (options.mudChance === undefined || options.mudChance === null
                ? 0.12 : options.mudChance) : options.mudThreshold;
        const ensureSolvable = options.ensureSolvable === undefined || options.ensureSolvable === null
            ? true : options.ensureSolvable;

        const maxAttempts = 10;
        let attempt = 0;
        let solvable = false;

        const startCell = this.getCell(0, 0);
        const goalCell = this.getCell(this.cols - 1, this.rows - 1);

        while (attempt < maxAttempts && !solvable) {
            attempt += 1;
            const noiseOffsetX = Math.random() * 1000;
            const noiseOffsetY = Math.random() * 1000;

            for (let row = 0; row < this.rows; row += 1) {
                for (let col = 0; col < this.cols; col += 1) {
                    // Células próximas amostram valores parecidos, formando regiões.
                    const terrainValue = noise(
                        noiseOffsetX + col * noiseScale,
                        noiseOffsetY + row * noiseScale
                    );

                    // Obstáculos são sorteados separadamente do terreno contínuo.
                    if (Math.random() < obstacleChance) {
                        this.setTerrain(col, row, Terrain.OBSTACLE);
                    } else if (terrainValue < waterThreshold) {
                        this.setTerrain(col, row, Terrain.WATER);
                    } else if (terrainValue < mudThreshold) {
                        this.setTerrain(col, row, Terrain.MUD);
                    } else {
                        this.setTerrain(col, row, Terrain.SAND);
                    }
                }
            }

            if (startCell) {
                startCell.setTerrain(Terrain.SAND);
            }

            if (goalCell) {
                goalCell.setTerrain(Terrain.SAND);
            }

            if (!ensureSolvable || this.isReachable(startCell, goalCell)) {
                solvable = true;
            }
        }

        if (ensureSolvable && !solvable && startCell && goalCell) {
            this.carveSolvablePath(startCell, goalCell);
        }
    }

    isReachable(startCell, goalCell) {
        if (!startCell || !goalCell || !startCell.walkable || !goalCell.walkable) {
            return false;
        }

        const queue = [startCell];
        const visited = new Set([startCell]);

        while (queue.length > 0) {
            const current = queue.shift();

            if (current === goalCell) {
                return true;
            }

            for (const neighbor of this.getNeighbors(current)) {
                if (!visited.has(neighbor)) {
                    visited.add(neighbor);
                    queue.push(neighbor);
                }
            }
        }

        return false;
    }

    carveSolvablePath(startCell, goalCell) {
        let currentCol = startCell.col;
        let currentRow = startCell.row;

        while (currentCol !== goalCell.col || currentRow !== goalCell.row) {
            const cell = this.getCell(currentCol, currentRow);
            if (cell && cell.terrainType === Terrain.OBSTACLE) {
                cell.setTerrain(Terrain.SAND);
            }

            const moveCol = currentCol < goalCell.col && (currentRow === goalCell.row || Math.random() < 0.5);

            if (moveCol) {
                currentCol += 1;
            } else if (currentRow < goalCell.row) {
                currentRow += 1;
            } else if (currentCol < goalCell.col) {
                currentCol += 1;
            }
        }

        goalCell.setTerrain(Terrain.SAND);
    }

    display() {
        for (const row of this.cells) {
            for (const cell of row) {
                cell.display(this.cellSize);
            }
        }
    }
}


// ========================================
// src/search/SearchAlgorithm.js
// ========================================
class SearchAlgorithm {
    constructor(grid, start, goal) {
        this.grid = grid;
        this.start = start;
        this.goal = goal;

        this.frontier = [];
        this.visited = [];
        this.finalPath = [];
        this.finished = false;
        this.found = false;
        this.cameFrom = new Map();
    }

    step() {
        // TODO: sobrescrever para processar somente um nó da busca.
    }

    isFinished() {
        return this.finished;
    }

    getPath() {
        return this.finalPath;
    }

    reconstructPath() {
        if (!this.found) {
            this.finalPath = [];
            return this.finalPath;
        }

        const path = [];
        let current = this.goal;

        while (current) {
            path.push(current);

            if (current === this.start) {
                break;
            }

            current = this.cameFrom.get(current);
        }

        if (path[path.length - 1] !== this.start) {
            this.finalPath = [];
            return this.finalPath;
        }

        this.finalPath = path.reverse();
        return this.finalPath;
    }

    finish(found) {
        this.finished = true;
        this.found = found;
        this.finalPath = found ? this.reconstructPath() : [];
    }

    reset() {
        this.frontier = [];
        this.visited = [];
        this.finalPath = [];
        this.finished = false;
        this.found = false;
        this.cameFrom = new Map();
    }
}


// ========================================
// src/search/PriorityQueue.js
// ========================================
class PriorityQueue {
    constructor() {
        this.items = [];
    }

    enqueue(element, priority) {
        const existingItem = this.items.find((item) => item.element === element);

        if (existingItem) {
            if (priority >= existingItem.priority) {
                return;
            }

            existingItem.priority = priority;
        } else {
            this.items.push({ element, priority });
        }

        this.items.sort((itemA, itemB) => itemA.priority - itemB.priority);
    }

    dequeue() {
        const item = this.items.shift();

        if (item) {
            return item.element;
        } else {
            return null;
        }
    }

    peek() {
        if (this.items.length > 0) {
            return this.items[0].element;
        } else {
            return null;
        }
    }

    isEmpty() {
        return this.items.length === 0;
    }

    size() {
        return this.items.length;
    }

    clear() {
        this.items = [];
    }

    contains(element) {
        return this.items.some((item) => item.element === element);
    }

    toArray() {
        return this.items.map((item) => item.element);
    }
}


// ========================================
// src/search/Heuristics.js
// ========================================
class Heuristics {
    static manhattan(cellA, cellB) {
        return Math.abs(cellA.col - cellB.col) + Math.abs(cellA.row - cellB.row);
    }
}


// ========================================
// src/search/BFS.js
// ========================================
class BFS extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.queue = [];
        this.discovered = new Set();

        this.init();
    }

    init() {
        if (this.start) {
            this.queue.push(this.start);
            this.frontier.push(this.start);
            this.discovered.add(this.start);
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.queue.length === 0) {
            this.finish(false);
            return;
        }

        const current = this.queue.shift();
        this.frontier = [...this.queue];
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            if (!this.discovered.has(neighbor)) {
                this.discovered.add(neighbor);
                this.cameFrom.set(neighbor, current);
                this.queue.push(neighbor);
                this.frontier.push(neighbor);
            }
        }
    }

    reset() {
        super.reset();
        this.queue = [];
        this.discovered = new Set();
        this.init();
    }
}


// ========================================
// src/search/DFS.js
// ========================================
class DFS extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.stack = [];
        this.discovered = new Set();

        this.init();
    }

    init() {
        if (this.start) {
            this.stack.push(this.start);
            this.frontier.push(this.start);
            this.discovered.add(this.start);
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.stack.length === 0) {
            this.finish(false);
            return;
        }

        // LIFO: o último nó empilhado é o próximo a ser processado.
        const current = this.stack.pop();
        this.frontier = [...this.stack];
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const neighbors = this.grid.getNeighbors(current);

        // Empilha em ordem reversa para que o primeiro vizinho de getNeighbors()
        // fique no topo da pilha e seja explorado primeiro.
        for (let i = neighbors.length - 1; i >= 0; i -= 1) {
            const neighbor = neighbors[i];

            if (!this.discovered.has(neighbor)) {
                this.discovered.add(neighbor);
                this.cameFrom.set(neighbor, current);
                this.stack.push(neighbor);
                this.frontier.push(neighbor);
            }
        }
    }

    reset() {
        super.reset();
        this.stack = [];
        this.discovered = new Set();
        this.init();
    }
}


// ========================================
// src/search/UniformCostSearch.js
// ========================================
class UniformCostSearch extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
        this.costSoFar = new Map();

        this.init();
    }

    init() {
        if (this.start) {
            // O custo inicial é zero: só cobramos a entrada nos vizinhos.
            this.costSoFar.set(this.start, 0);
            this.priorityQueue.enqueue(this.start, 0);
            this.frontier = this.priorityQueue.toArray();
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.priorityQueue.isEmpty()) {
            this.finish(false);
            return;
        }

        const current = this.priorityQueue.dequeue();
        this.frontier = this.priorityQueue.toArray();
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const currentCost = this.costSoFar.get(current);
        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            // Com custos não negativos, um nó expandido já tem custo mínimo.
            if (this.visited.includes(neighbor)) {
                continue;
            }

            const newCost = currentCost + neighbor.cost;
            const knownCost = this.costSoFar.get(neighbor);

            if (!this.costSoFar.has(neighbor) || newCost < knownCost) {
                this.costSoFar.set(neighbor, newCost);
                this.cameFrom.set(neighbor, current);
                this.priorityQueue.enqueue(neighbor, newCost);
            }
        }

        this.frontier = this.priorityQueue.toArray();
    }

    reset() {
        super.reset();
        this.priorityQueue.clear();
        this.costSoFar.clear();
        this.init();
    }
}


// ========================================
// src/search/GreedySearch.js
// ========================================
class GreedySearch extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
        this.discovered = new Set();

        this.init();
    }

    init() {
        if (this.start) {
            this.discovered.add(this.start);
            this.priorityQueue.enqueue(this.start, Heuristics.manhattan(this.start, this.goal));
            this.frontier = this.priorityQueue.toArray();
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.priorityQueue.isEmpty()) {
            this.finish(false);
            return;
        }

        // A gulosa ignora o custo acumulado: expande o nó que parece mais perto do objetivo.
        const current = this.priorityQueue.dequeue();
        this.visited.push(current);

        if (current === this.goal) {
            this.frontier = this.priorityQueue.toArray();
            this.finish(true);
            return;
        }

        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            if (!this.discovered.has(neighbor)) {
                this.discovered.add(neighbor);
                this.cameFrom.set(neighbor, current);
                this.priorityQueue.enqueue(neighbor, Heuristics.manhattan(neighbor, this.goal));
            }
        }

        this.frontier = this.priorityQueue.toArray();
    }

    reset() {
        super.reset();
        this.priorityQueue.clear();
        this.discovered = new Set();
        this.init();
    }
}


// ========================================
// src/search/AStar.js
// ========================================
class AStar extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
        this.costSoFar = new Map();
        this.closed = new Set();
        this.minimumStepCost = AStar.getMinimumStepCost();

        this.init();
    }

    init() {
        if (this.start) {
            this.costSoFar.set(this.start, 0);
            this.priorityQueue.enqueue(this.start, this.getPriority(this.start, 0));
            this.frontier = this.priorityQueue.toArray();
        }
    }

    heuristic(cell) {
        // Manhattan conta passos; cada passo custa pelo menos o terreno mais barato.
        // Multiplicar por esse custo mantém a heurística admissível e consistente,
        // mas na mesma escala dos custos, o que deixa a A* bem mais focada que a UCS.
        return Heuristics.manhattan(cell, this.goal) * this.minimumStepCost;
    }

    getPriority(cell, costToCell) {
        const estimate = this.heuristic(cell);

        // Em empates de f = g + h, prefere o nó mais perto do objetivo.
        // O desempate é menor que qualquer diferença de custo, então não muda a ordem por f.
        return costToCell + estimate + estimate * AStar.TIE_BREAK;
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.priorityQueue.isEmpty()) {
            this.finish(false);
            return;
        }

        const current = this.priorityQueue.dequeue();
        this.closed.add(current);
        this.visited.push(current);

        if (current === this.goal) {
            this.frontier = this.priorityQueue.toArray();
            this.finish(true);
            return;
        }

        const currentCost = this.costSoFar.get(current);
        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            // Com heurística consistente, um nó expandido já tem custo mínimo.
            if (this.closed.has(neighbor)) {
                continue;
            }

            const newCost = currentCost + neighbor.cost;

            if (!this.costSoFar.has(neighbor) || newCost < this.costSoFar.get(neighbor)) {
                this.costSoFar.set(neighbor, newCost);
                this.cameFrom.set(neighbor, current);
                this.priorityQueue.enqueue(neighbor, this.getPriority(neighbor, newCost));
            }
        }

        this.frontier = this.priorityQueue.toArray();
    }

    reset() {
        super.reset();
        this.priorityQueue.clear();
        this.costSoFar.clear();
        this.closed = new Set();
        this.init();
    }

    static getMinimumStepCost() {
        let minimum = Infinity;

        for (const type of Object.keys(Terrain.TYPES)) {
            if (Terrain.isWalkable(type)) {
                minimum = Math.min(minimum, Terrain.getCost(type));
            }
        }

        return minimum;
    }
}

AStar.TIE_BREAK = 1e-6;


// ========================================
// src/agent/Agent.js
// ========================================
class Agent {
    constructor(position) {
        this.position = position;
        this.path = [];
        this.currentPathIndex = 0;
        this.isMoving = false;
        // Fração (0 a 1) já percorrida entre a célula atual e a próxima do caminho.
        this.stepProgress = 0;
    }

    setPosition(cell) {
        this.position = cell;
        this.stepProgress = 0;
    }

    setPath(path) {
        this.path = path;
        this.currentPathIndex = 0;
        this.stepProgress = 0;
        this.isMoving = path.length > 1;

        if (path.length > 0) {
            this.position = path[0];
        }
    }

    clearPath() {
        this.path = [];
        this.currentPathIndex = 0;
        this.stepProgress = 0;
        this.isMoving = false;
    }

    getTerrainSpeedMultiplier() {
        if (!this.position) {
            return 0;
        }

        return Terrain.getSpeedMultiplier(this.position.terrainType);
    }

    getNextCell() {
        return this.path[this.currentPathIndex + 1] || null;
    }

    hasReachedEnd() {
        return this.path.length > 0 && this.currentPathIndex === this.path.length - 1;
    }

    update(deltaMs = Agent.getFrameDelta()) {
        if (!this.isMoving) {
            return;
        }

        let remainingSeconds = Math.min(deltaMs, Agent.MAX_FRAME_DELTA_MS) / 1000;

        while (remainingSeconds > 0 && this.isMoving) {
            const nextCell = this.getNextCell();

            // A velocidade vem do terreno em que o agente está entrando,
            // coerente com o custo de entrada usado pelas buscas.
            const multiplier = Terrain.getSpeedMultiplier(nextCell.terrainType);
            const cellsPerSecond = Agent.BASE_SPEED * multiplier;

            if (cellsPerSecond <= 0) {
                this.isMoving = false;
                return;
            }

            const secondsToNextCell = (1 - this.stepProgress) / cellsPerSecond;

            if (remainingSeconds < secondsToNextCell) {
                this.stepProgress += remainingSeconds * cellsPerSecond;
                return;
            }

            remainingSeconds -= secondsToNextCell;
            this.currentPathIndex += 1;
            this.position = nextCell;
            this.stepProgress = 0;

            if (this.hasReachedEnd()) {
                this.isMoving = false;
            }
        }
    }

    display(cellSize) {
        if (!this.position) {
            return;
        }

        let col = this.position.col;
        let row = this.position.row;
        const nextCell = this.isMoving ? this.getNextCell() : null;

        // Interpola entre as células para o movimento parecer contínuo.
        if (nextCell) {
            col += (nextCell.col - col) * this.stepProgress;
            row += (nextCell.row - row) * this.stepProgress;
        }

        const centerX = col * cellSize + cellSize / 2;
        const centerY = row * cellSize + cellSize / 2;

        noStroke();
        fill(220, 50, 50);
        circle(centerX, centerY, cellSize * 0.55);
    }

    static getFrameDelta() {
        // deltaTime é fornecido pelo p5.js; fora do navegador assume 60 FPS.
        return typeof deltaTime === "number" ? deltaTime : 1000 / 60;
    }
}

// Células por segundo em areia; lama e água reduzem pelo multiplicador do terreno.
Agent.BASE_SPEED = 5;
// Evita saltos de várias células quando a aba fica em segundo plano.
Agent.MAX_FRAME_DELTA_MS = 100;


// ========================================
// src/entities/Food.js
// ========================================
class Food {
    constructor(position) {
        this.position = position;
    }

    setPosition(cell) {
        this.position = cell;
    }

    relocate(grid, agentCell) {
        const previousPosition = this.position;
        const maxDistance = (grid.cols - 1) + (grid.rows - 1);
        const minimumDistance = Math.ceil(maxDistance * 0.45);
        const reachableCells = [];
        const pendingCells = [];
        const seen = new Set();

        if (agentCell && agentCell.walkable) {
            pendingCells.push(agentCell);
            seen.add(agentCell);
        }

        // Uma única travessia encontra o componente alcançável do agente.
        while (pendingCells.length > 0) {
            const currentCell = pendingCells.pop();

            if (currentCell !== agentCell) {
                reachableCells.push(currentCell);
            }

            for (const neighbor of grid.getNeighbors(currentCell)) {
                if (neighbor.walkable && !seen.has(neighbor)) {
                    seen.add(neighbor);
                    pendingCells.push(neighbor);
                }
            }
        }

        const distanceFromAgent = (cell) => Math.abs(cell.col - agentCell.col)
            + Math.abs(cell.row - agentCell.row);
        let candidates = reachableCells.filter((cell) => distanceFromAgent(cell) >= minimumDistance);

        // Se a distância preferida for impossível, use as células mais distantes.
        if (candidates.length === 0) {
            let farthestDistance = 0;

            for (const cell of reachableCells) {
                farthestDistance = Math.max(farthestDistance, distanceFromAgent(cell));
            }

            candidates = reachableCells.filter((cell) => distanceFromAgent(cell) === farthestDistance);
        }

        if (previousPosition && candidates.length > 1) {
            candidates = candidates.filter((cell) => cell.col !== previousPosition.col
                || cell.row !== previousPosition.row);
        }

        // Uma grade sem outra célula alcançável não tem um objetivo válido.
        if (candidates.length === 0) {
            this.position = null;
            return null;
        }

        const selectedCell = candidates[Math.floor(Math.random() * candidates.length)];
        this.setPosition(selectedCell);
        return selectedCell;
    }

    display(cellSize) {
        if (!this.position) {
            return;
        }

        const centerX = this.position.col * cellSize + cellSize / 2;
        const centerY = this.position.row * cellSize + cellSize / 2;

        noStroke();
        fill(60, 170, 75);
        circle(centerX, centerY, cellSize * 0.4);
    }
}


// ========================================
// src/ui/UI.js
// ========================================
class UI {
    constructor() {
        this.availableAlgorithms = ["BFS", "DFS", "UCS", "GREEDY", "ASTAR"];
        this.selectedAlgorithm = "BFS";
        this.speed = 1;
        this.pendingActions = [];
        this.controls = null;
        this.lastStatusHtml = "";
    }

    initialize() {
        // Fora do navegador (testes em Node) não há funções de DOM do p5.js.
        if (typeof createDiv !== "function") {
            return;
        }

        const panel = createDiv();
        panel.addClass("panel");
        createElement("h1", "Busca Inteligente em Grid").parent(panel);

        this.controls = {
            algorithmSelect: this.createAlgorithmSelect(panel),
            speedSlider: null,
            speedLabel: null,
            status: null
        };

        this.createActionButtons(panel);
        this.createSpeedControl(panel);

        this.controls.status = createDiv();
        this.controls.status.addClass("status");
        this.controls.status.parent(panel);

        this.createLegend(panel);
    }

    createAlgorithmSelect(panel) {
        const group = this.createGroup(panel, "Algoritmo");
        const select = createSelect();

        for (const name of this.availableAlgorithms) {
            select.option(UI.ALGORITHM_LABELS[name], name);
        }

        select.selected(this.selectedAlgorithm);
        select.parent(group);
        return select;
    }

    createActionButtons(panel) {
        const group = createDiv();
        group.addClass("buttons");
        group.parent(panel);

        const buttons = [
            { label: "Iniciar busca", action: UI.ACTIONS.START, primary: true },
            { label: "Reiniciar", action: UI.ACTIONS.RESET },
            { label: "Novo mapa", action: UI.ACTIONS.NEW_MAP }
        ];

        for (const definition of buttons) {
            const button = createButton(definition.label);
            button.parent(group);
            button.mousePressed(() => this.requestAction(definition.action));

            if (definition.primary) {
                button.addClass("primary");
            }
        }
    }

    createSpeedControl(panel) {
        const group = this.createGroup(panel, "Velocidade");
        const row = createDiv();
        row.addClass("speed");
        row.parent(group);

        this.controls.speedSlider = createSlider(UI.MIN_SPEED, UI.MAX_SPEED, this.speed, UI.SPEED_STEP);
        this.controls.speedSlider.parent(row);

        this.controls.speedLabel = createSpan(this.formatSpeed(this.speed));
        this.controls.speedLabel.parent(row);
    }

    createLegend(panel) {
        const legend = createDiv();
        legend.addClass("legend");
        legend.parent(panel);

        let html = "<h2>Terrenos</h2><ul>";

        for (const properties of Object.values(Terrain.TYPES)) {
            const cost = properties.walkable ? `custo ${properties.cost}` : "intransponível";
            html += this.legendItem(properties.color, `${properties.label} (${cost})`);
        }

        const colors = SearchVisualizer.COLORS;
        html += "</ul><h2>Busca</h2><ul>";
        html += this.legendItem(colors.visited, "Visitados");
        html += this.legendItem(colors.frontier, "Fronteira");
        html += this.legendItem(colors.path, "Caminho final");
        html += this.legendItem(UI.AGENT_COLOR, "Agente");
        html += this.legendItem(UI.FOOD_COLOR, "Comida");
        html += "</ul>";

        legend.html(html);
    }

    createGroup(panel, title) {
        const group = createDiv();
        group.addClass("group");
        group.parent(panel);
        createSpan(title).addClass("group-title").parent(group);
        return group;
    }

    legendItem(color, label) {
        return `<li><span class="swatch" style="background: rgb(${color[0]}, ${color[1]}, ${color[2]})"></span>${label}</li>`;
    }

    setSelectedAlgorithm(name) {
        if (this.availableAlgorithms.includes(name)) {
            this.selectedAlgorithm = name;

            if (this.controls) {
                this.controls.algorithmSelect.selected(name);
            }

            return true;
        }

        return false;
    }

    getSelectedAlgorithm() {
        return this.selectedAlgorithm;
    }

    getSpeed() {
        return this.speed;
    }

    requestAction(action) {
        this.pendingActions.push(action);
    }

    consumeActions() {
        const actions = this.pendingActions;
        this.pendingActions = [];
        return actions;
    }

    update() {
        if (!this.controls) {
            return;
        }

        const selected = this.controls.algorithmSelect.value();

        if (this.availableAlgorithms.includes(selected)) {
            this.selectedAlgorithm = selected;
        }

        this.speed = Number(this.controls.speedSlider.value());
    }

    display(status) {
        if (!this.controls || !status) {
            return;
        }

        this.controls.speedLabel.html(this.formatSpeed(this.speed));

        // Só reescreve o painel quando algo muda, para não refazer o DOM a cada quadro.
        const html = this.buildStatusHtml(status);

        if (html !== this.lastStatusHtml) {
            this.controls.status.html(html);
            this.lastStatusHtml = html;
        }
    }

    buildStatusHtml(status) {
        let html = `<p class="state state-${status.state.toLowerCase()}">${UI.STATE_LABELS[status.state]}</p>`;

        if (status.message) {
            html += `<p class="message">${status.message}</p>`;
        }

        html += "<dl>";
        html += `<dt>Algoritmo</dt><dd>${UI.ALGORITHM_LABELS[status.algorithm]}</dd>`;
        html += `<dt>Nós visitados</dt><dd>${status.visited}</dd>`;
        html += `<dt>Fronteira</dt><dd>${status.frontier}</dd>`;
        html += `<dt>Passos do caminho</dt><dd>${status.pathSteps}</dd>`;
        html += `<dt>Custo do caminho</dt><dd>${status.pathCost}</dd>`;
        html += `<dt>Comidas coletadas</dt><dd>${status.score}</dd>`;
        html += "</dl>";

        return html + this.buildResultsHtml(status.results);
    }

    buildResultsHtml(results) {
        if (!results || results.size === 0) {
            return "";
        }

        let html = "<h2>Comparação neste mapa</h2><table><thead><tr>";
        html += "<th>Algoritmo</th><th>Visitados</th><th>Passos</th><th>Custo</th>";
        html += "</tr></thead><tbody>";

        for (const name of this.availableAlgorithms) {
            const result = results.get(name);

            if (!result) {
                continue;
            }

            const steps = result.found ? result.pathSteps : "—";
            const cost = result.found ? result.pathCost : "sem caminho";
            html += `<tr><td>${name === "ASTAR" ? "A*" : name}</td><td>${result.visited}</td>`;
            html += `<td>${steps}</td><td>${cost}</td></tr>`;
        }

        return html + "</tbody></table>";
    }

    formatSpeed(speed) {
        return `${speed}x`;
    }
}

UI.ACTIONS = Object.freeze({
    START: "START",
    RESET: "RESET",
    NEW_MAP: "NEW_MAP"
});

UI.ALGORITHM_LABELS = Object.freeze({
    BFS: "Busca em Largura (BFS)",
    DFS: "Busca em Profundidade (DFS)",
    UCS: "Custo Uniforme (UCS)",
    GREEDY: "Gulosa (Melhor Primeiro)",
    ASTAR: "A*"
});

UI.STATE_LABELS = Object.freeze({
    WAITING: "Aguardando",
    SEARCHING: "Buscando…",
    MOVING: "Agente a caminho da comida",
    COLLECTING: "Comida alcançada!"
});

UI.MIN_SPEED = 0.25;
UI.MAX_SPEED = 4;
UI.SPEED_STEP = 0.25;

// Mesmas cores usadas em Agent.display() e Food.display().
UI.AGENT_COLOR = Object.freeze([220, 50, 50]);
UI.FOOD_COLOR = Object.freeze([60, 170, 75]);


// ========================================
// src/ui/SearchVisualizer.js
// ========================================
class SearchVisualizer {
    constructor(cellSize) {
        this.cellSize = cellSize;

        // Estado apenas visual: não altera a busca nem o ciclo da simulação.
        this.trackedSearch = null;
        this.pathFrames = 0;
    }

    display(search) {
        if (!search) {
            return;
        }

        this.updatePathAnimation(search);

        this.drawVisited(search.visited);
        this.drawFrontier(search.frontier);
        this.drawCurrent(search);
        this.drawPath(search.finalPath);
    }

    updatePathAnimation(search) {
        // Reinicia a animação quando uma nova busca começa ou a atual é reiniciada.
        if (search !== this.trackedSearch || search.finalPath.length === 0) {
            this.trackedSearch = search;
            this.pathFrames = 0;
        } else {
            this.pathFrames += 1;
        }
    }

    drawVisited(visited) {
        const colors = SearchVisualizer.COLORS;
        const trailLength = SearchVisualizer.TRAIL_LENGTH;
        const trailStart = visited.length - trailLength;

        push();
        noStroke();

        for (let i = 0; i < visited.length; i += 1) {
            // Os nós visitados mais recentemente ficam mais intensos,
            // formando um rastro que mostra o avanço da busca passo a passo.
            const recency = i >= trailStart ? (i - trailStart + 1) / trailLength : 0;
            const visitedOpacity = colors.visitedAlpha + (colors.trailAlpha - colors.visitedAlpha) * recency;

            fill(...colors.visited, visitedOpacity);
            this.drawCell(visited[i], 1);
        }

        pop();
    }

    drawFrontier(frontier) {
        const colors = SearchVisualizer.COLORS;

        push();
        stroke(...colors.frontierStroke);
        strokeWeight(2);
        fill(...colors.frontier);

        for (const cell of frontier) {
            this.drawCell(cell, this.cellSize * 0.25);
        }

        pop();
    }

    drawCurrent(search) {
        // O último nó visitado é o que acabou de ser expandido.
        if (search.isFinished() || search.visited.length === 0) {
            return;
        }

        const current = search.visited[search.visited.length - 1];

        push();
        noFill();
        stroke(...SearchVisualizer.COLORS.current);
        strokeWeight(3);
        this.drawCell(current, 2);
        pop();
    }

    drawPath(path) {
        if (!path || path.length === 0) {
            return;
        }

        const colors = SearchVisualizer.COLORS;
        const visibleCells = this.getVisiblePathLength(path);

        push();
        noFill();

        // O contorno escuro deixa o caminho legível sobre qualquer terreno.
        stroke(...colors.pathOutline);
        strokeWeight(this.cellSize * 0.3);
        this.drawPathSegments(path, visibleCells);

        stroke(...colors.path);
        strokeWeight(this.cellSize * 0.16);
        this.drawPathSegments(path, visibleCells);

        pop();
    }

    drawPathSegments(path, visibleCells) {
        if (visibleCells === 1) {
            const center = this.getCenter(path[0]);
            point(center.x, center.y);
            return;
        }

        for (let i = 1; i < visibleCells; i += 1) {
            const from = this.getCenter(path[i - 1]);
            const to = this.getCenter(path[i]);
            line(from.x, from.y, to.x, to.y);
        }
    }

    getVisiblePathLength(path) {
        // O caminho é revelado do início ao objetivo, uma célula a cada poucos quadros.
        const revealed = 1 + Math.floor(this.pathFrames / SearchVisualizer.PATH_FRAMES_PER_CELL);
        return Math.min(path.length, revealed);
    }

    getCenter(cell) {
        return {
            x: cell.col * this.cellSize + this.cellSize / 2,
            y: cell.row * this.cellSize + this.cellSize / 2
        };
    }

    drawCell(cell, inset) {
        rect(
            cell.col * this.cellSize + inset,
            cell.row * this.cellSize + inset,
            this.cellSize - inset * 2,
            this.cellSize - inset * 2
        );
    }
}

SearchVisualizer.TRAIL_LENGTH = 12;
SearchVisualizer.PATH_FRAMES_PER_CELL = 2;

SearchVisualizer.COLORS = Object.freeze({
    visited: Object.freeze([95, 55, 135]),
    visitedAlpha: 120,
    trailAlpha: 220,
    frontier: Object.freeze([255, 130, 20, 225]),
    frontierStroke: Object.freeze([130, 60, 0]),
    current: Object.freeze([255, 255, 255]),
    path: Object.freeze([255, 225, 0]),
    pathOutline: Object.freeze([35, 35, 35, 225])
});


// ========================================
// src/core/SimulationState.js
// ========================================
const SimulationState = Object.freeze({
    WAITING: "WAITING",
    SEARCHING: "SEARCHING",
    MOVING: "MOVING",
    COLLECTING: "COLLECTING"
});


// ========================================
// src/core/Simulation.js
// ========================================
class Simulation {
    constructor(options = {}) {
        const cols = options.cols || 20;
        const rows = options.rows || 15;
        const cellSize = options.cellSize || 40;

        this.grid = new Grid(cols, rows, cellSize);
        this.initialAgentCell = this.grid.getRandomWalkableCell();
        this.agent = new Agent(this.initialAgentCell);
        this.food = new Food(null);
        this.food.relocate(this.grid, this.agent.position);
        this.ui = new UI();
        this.searchVisualizer = new SearchVisualizer(cellSize);
        this.search = null;
        this.searchAlgorithmName = null;
        this.stepBudget = 0;
        this.score = 0;
        this.message = "Gere um novo mapa ou inicie uma busca.";
        // Só compare resultados com o mesmo início e objetivo no mapa atual.
        this.results = new Map();
        this.resultsStart = null;
        this.resultsGoal = null;
        this.state = SimulationState.WAITING;

        this.ui.initialize();
    }

    generateNewMap() {
        this.grid.generateProcedural();

        const startCell = this.grid.getRandomWalkableCell();
        this.initialAgentCell = startCell;
        this.agent.setPosition(startCell);
        this.agent.clearPath();
        this.food.relocate(this.grid, startCell);
        this.search = null;
        this.searchAlgorithmName = null;
        this.stepBudget = 0;
        this.results.clear();
        this.resultsStart = null;
        this.resultsGoal = null;
        this.message = "Novo mapa gerado. Escolha um algoritmo e inicie a busca.";
        this.setState(SimulationState.WAITING);
    }

    resetSimulation() {
        this.generateNewMap();
    }

    update() {
        this.ui.update();
        this.handleUIActions();

        if (this.state === SimulationState.WAITING) {
            this.updateWaiting();
        } else if (this.state === SimulationState.SEARCHING) {
            this.updateSearching();
        } else if (this.state === SimulationState.MOVING) {
            this.updateMoving();
        } else if (this.state === SimulationState.COLLECTING) {
            this.updateCollecting();
        }
    }

    handleUIActions() {
        for (const action of this.ui.consumeActions()) {
            if (action === UI.ACTIONS.START) {
                this.startSearch();
            } else if (action === UI.ACTIONS.RESET) {
                this.resetSimulation();
            } else if (action === UI.ACTIONS.NEW_MAP) {
                this.generateNewMap();
            }
        }
    }

    updateWaiting() {
        // A simulação aguarda o usuário iniciar uma busca.
    }

    updateSearching() {
        if (!this.search) {
            return;
        }

        // A velocidade define quantos step() rodam por quadro; abaixo de 1x,
        // o orçamento acumula e a busca avança um nó a cada poucos quadros.
        this.stepBudget += this.ui.getSpeed();

        while (this.stepBudget >= 1 && !this.search.isFinished()) {
            this.search.step();
            this.stepBudget -= 1;
        }

        if (this.search.isFinished()) {
            this.handleSearchFinished();
        }
    }

    handleSearchFinished() {
        this.recordResult();

        if (!this.search.found) {
            this.message = "Nenhum caminho até a comida foi encontrado.";
            this.setState(SimulationState.WAITING);
            return;
        }

        this.agent.setPath(this.search.getPath());

        if (this.agent.isMoving) {
            this.message = "";
            this.setState(SimulationState.MOVING);
        } else {
            this.collectFood();
        }
    }

    updateMoving() {
        this.agent.update(Agent.getFrameDelta() * this.ui.getSpeed());

        if (!this.agent.isMoving) {
            this.collectFood();
        }
    }

    collectFood() {
        if (this.state === SimulationState.COLLECTING) {
            return;
        }

        if (!this.food.position || this.agent.position !== this.food.position) {
            this.message = "O agente parou antes de alcançar a comida.";
            this.setState(SimulationState.WAITING);
            return;
        }

        this.score += 1;
        this.message = "Comida coletada! A próxima busca começará da posição atual.";
        this.setState(SimulationState.COLLECTING);
    }

    updateCollecting() {
        this.food.relocate(this.grid, this.agent.position);
        this.results.clear();
        this.search = null;
        this.searchAlgorithmName = null;
        this.startSearch({ resetAgent: false });
    }

    startSearch(options = {}) {
        if (!this.food.position) {
            this.message = "Não há comida alcançável neste mapa.";
            this.setState(SimulationState.WAITING);
            return;
        }

        // O início manual preserva a comparação; a coleta continua da célula atual.
        if (options.resetAgent !== false) {
            this.agent.setPosition(this.initialAgentCell);
        }

        this.agent.clearPath();

        if (this.resultsStart !== this.agent.position || this.resultsGoal !== this.food.position) {
            this.results.clear();
        }

        this.resultsStart = this.agent.position;
        this.resultsGoal = this.food.position;
        const algorithmName = this.ui.getSelectedAlgorithm();

        this.search = this.createSearchAlgorithm(
            algorithmName,
            this.agent.position,
            this.food.position
        );
        this.searchAlgorithmName = algorithmName;
        this.stepBudget = 0;
        this.message = "";

        this.setState(SimulationState.SEARCHING);
    }

    createSearchAlgorithm(algorithmName, start, goal) {
        if (algorithmName === "BFS") {
            return new BFS(this.grid, start, goal);
        }

        if (algorithmName === "DFS") {
            return new DFS(this.grid, start, goal);
        }

        if (algorithmName === "UCS") {
            return new UniformCostSearch(this.grid, start, goal);
        }

        if (algorithmName === "GREEDY") {
            return new GreedySearch(this.grid, start, goal);
        }

        if (algorithmName === "ASTAR") {
            return new AStar(this.grid, start, goal);
        }

        throw new Error(`Algoritmo desconhecido: ${algorithmName}`);
    }

    recordResult() {
        const path = this.search.getPath();

        this.results.set(this.searchAlgorithmName, {
            found: this.search.found,
            visited: this.search.visited.length,
            pathSteps: Math.max(path.length - 1, 0),
            pathCost: this.getPathCost(path)
        });
    }

    getPathCost(path) {
        // O custo de um passo é o custo de entrar na célula; o início não é cobrado.
        let total = 0;

        for (let i = 1; i < path.length; i += 1) {
            total += path[i].cost;
        }

        return total;
    }

    getStatus() {
        const search = this.search;
        const path = search ? search.getPath() : [];

        return {
            state: this.state,
            algorithm: this.searchAlgorithmName || this.ui.getSelectedAlgorithm(),
            visited: search ? search.visited.length : 0,
            frontier: search ? search.frontier.length : 0,
            pathSteps: Math.max(path.length - 1, 0),
            pathCost: this.getPathCost(path),
            score: this.score,
            message: this.message,
            results: this.results
        };
    }

    display() {
        this.grid.display();
        this.searchVisualizer.display(this.search);
        this.food.display(this.grid.cellSize);
        this.agent.display(this.grid.cellSize);
        this.ui.display(this.getStatus());
    }

    setState(state) {
        if (!Object.values(SimulationState).includes(state)) {
            throw new Error(`Estado de simulação inválido: ${state}`);
        }

        this.state = state;
    }
}


// ========================================
// sketch.js
// ========================================
let simulation;

function setup() {
    createCanvas(800, 600);

    simulation = new Simulation({
        cols: 20,
        rows: 15,
        cellSize: 40
    });
    simulation.generateNewMap();
}

function draw() {
    background(245);

    simulation.update();
    simulation.display();
}

