// Generated by scripts/build-web-editor.sh. Edit src/ or root sketch.js, then regenerate.

// ========================================
// src/world/Terrain.js
// ========================================
class Terrain {
    static getProperties(type) {
        const properties = Terrain.TYPES[type];

        if (!properties) {
            throw new Error(`Tipo de terreno inválido: ${type}`);
        }

        return properties;
    }

    static getCost(type) {
        return Terrain.getProperties(type).cost;
    }

    static getSpeedMultiplier(type) {
        return Terrain.getProperties(type).speedMultiplier;
    }

    static isWalkable(type) {
        return Terrain.getProperties(type).walkable;
    }

    static getColor(type) {
        return Terrain.getProperties(type).color;
    }
}

Terrain.SAND = "SAND";
Terrain.MUD = "MUD";
Terrain.WATER = "WATER";
Terrain.OBSTACLE = "OBSTACLE";

Terrain.TYPES = Object.freeze({
    SAND: Object.freeze({
        label: "Areia",
        cost: 10,
        speedMultiplier: 1,
        walkable: true,
        color: Object.freeze([224, 196, 126])
    }),
    MUD: Object.freeze({
        label: "Atoleiro",
        cost: 50,
        speedMultiplier: 0.6,
        walkable: true,
        color: Object.freeze([132, 94, 61])
    }),
    WATER: Object.freeze({
        label: "Água",
        cost: 100,
        speedMultiplier: 0.3,
        walkable: true,
        color: Object.freeze([79, 151, 205])
    }),
    OBSTACLE: Object.freeze({
        label: "Obstáculo",
        cost: Infinity,
        speedMultiplier: 0,
        walkable: false,
        color: Object.freeze([55, 55, 55])
    })
});


// ========================================
// src/world/Cell.js
// ========================================
class Cell {
    constructor(col, row, terrainType = Terrain.SAND) {
        this.position = { col, row };
        this.terrainType = terrainType;
        this.neighbors = [];
    }

    get col() {
        return this.position.col;
    }

    get row() {
        return this.position.row;
    }

    get cost() {
        return Terrain.getCost(this.terrainType);
    }

    get walkable() {
        return Terrain.isWalkable(this.terrainType);
    }

    setTerrain(terrainType) {
        Terrain.getProperties(terrainType);
        this.terrainType = terrainType;
    }

    addNeighbor(cell) {
        if (!this.neighbors.includes(cell)) {
            this.neighbors.push(cell);
        }
    }

    clearNeighbors() {
        this.neighbors = [];
    }

    display(cellSize) {
        const terrainColor = Terrain.getColor(this.terrainType);
        const x = this.col * cellSize;
        const y = this.row * cellSize;

        stroke(180);
        strokeWeight(1);
        fill(...terrainColor);
        rect(x, y, cellSize, cellSize);
    }
}


// ========================================
// src/world/Grid.js
// ========================================
class Grid {
    constructor(cols, rows, cellSize) {
        this.cols = cols;
        this.rows = rows;
        this.cellSize = cellSize;
        this.cells = [];

        this.createCells();
        this.connectNeighbors();
    }

    createCells() {
        for (let row = 0; row < this.rows; row += 1) {
            const currentRow = [];

            for (let col = 0; col < this.cols; col += 1) {
                currentRow.push(new Cell(col, row, Terrain.SAND));
            }

            this.cells.push(currentRow);
        }
    }

    connectNeighbors() {
        const directions = [
            { col: 0, row: -1 },
            { col: 1, row: 0 },
            { col: 0, row: 1 },
            { col: -1, row: 0 }
        ];

        for (let row = 0; row < this.rows; row += 1) {
            for (let col = 0; col < this.cols; col += 1) {
                const cell = this.getCell(col, row);
                cell.clearNeighbors();

                for (const direction of directions) {
                    const neighbor = this.getCell(
                        col + direction.col,
                        row + direction.row
                    );

                    if (neighbor) {
                        cell.addNeighbor(neighbor);
                    }
                }
            }
        }
    }

    getCell(col, row) {
        if (!this.isInside(col, row)) {
            return null;
        }

        return this.cells[row][col];
    }

    isInside(col, row) {
        return col >= 0 && col < this.cols && row >= 0 && row < this.rows;
    }

    getNeighbors(cell) {
        return cell.neighbors.filter((neighbor) => neighbor.walkable);
    }

    setTerrain(col, row, terrainType) {
        const cell = this.getCell(col, row);

        if (!cell) {
            return false;
        }

        cell.setTerrain(terrainType);
        return true;
    }

    generateProcedural(options = {}) {
        const obstacleChance = options.obstacleChance === undefined || options.obstacleChance === null
            ? 0.15 : options.obstacleChance;
        const mudChance = options.mudChance === undefined || options.mudChance === null
            ? 0.15 : options.mudChance;
        const waterChance = options.waterChance === undefined || options.waterChance === null
            ? 0.10 : options.waterChance;
        const ensureSolvable = options.ensureSolvable === undefined || options.ensureSolvable === null
            ? true : options.ensureSolvable;

        const maxAttempts = 10;
        let attempt = 0;
        let solvable = false;

        const startCell = this.getCell(0, 0);
        const goalCell = this.getCell(this.cols - 1, this.rows - 1);

        while (attempt < maxAttempts && !solvable) {
            attempt += 1;

            for (let row = 0; row < this.rows; row += 1) {
                for (let col = 0; col < this.cols; col += 1) {
                    const roll = Math.random();

                    if (roll < obstacleChance) {
                        this.setTerrain(col, row, Terrain.OBSTACLE);
                    } else if (roll < obstacleChance + mudChance) {
                        this.setTerrain(col, row, Terrain.MUD);
                    } else if (roll < obstacleChance + mudChance + waterChance) {
                        this.setTerrain(col, row, Terrain.WATER);
                    } else {
                        this.setTerrain(col, row, Terrain.SAND);
                    }
                }
            }

            if (startCell) {
                startCell.setTerrain(Terrain.SAND);
            }

            if (goalCell) {
                goalCell.setTerrain(Terrain.SAND);
            }

            if (!ensureSolvable || this.isReachable(startCell, goalCell)) {
                solvable = true;
            }
        }

        if (ensureSolvable && !solvable && startCell && goalCell) {
            this.carveSolvablePath(startCell, goalCell);
        }
    }

    isReachable(startCell, goalCell) {
        if (!startCell || !goalCell || !startCell.walkable || !goalCell.walkable) {
            return false;
        }

        const queue = [startCell];
        const visited = new Set([startCell]);

        while (queue.length > 0) {
            const current = queue.shift();

            if (current === goalCell) {
                return true;
            }

            for (const neighbor of this.getNeighbors(current)) {
                if (!visited.has(neighbor)) {
                    visited.add(neighbor);
                    queue.push(neighbor);
                }
            }
        }

        return false;
    }

    carveSolvablePath(startCell, goalCell) {
        let currentCol = startCell.col;
        let currentRow = startCell.row;

        while (currentCol !== goalCell.col || currentRow !== goalCell.row) {
            const cell = this.getCell(currentCol, currentRow);
            if (cell && cell.terrainType === Terrain.OBSTACLE) {
                cell.setTerrain(Terrain.SAND);
            }

            const moveCol = currentCol < goalCell.col && (currentRow === goalCell.row || Math.random() < 0.5);

            if (moveCol) {
                currentCol += 1;
            } else if (currentRow < goalCell.row) {
                currentRow += 1;
            } else if (currentCol < goalCell.col) {
                currentCol += 1;
            }
        }

        goalCell.setTerrain(Terrain.SAND);
    }

    display() {
        for (const row of this.cells) {
            for (const cell of row) {
                cell.display(this.cellSize);
            }
        }
    }
}


// ========================================
// src/search/SearchAlgorithm.js
// ========================================
class SearchAlgorithm {
    constructor(grid, start, goal) {
        this.grid = grid;
        this.start = start;
        this.goal = goal;

        this.frontier = [];
        this.visited = [];
        this.finalPath = [];
        this.finished = false;
        this.found = false;
        this.cameFrom = new Map();
    }

    step() {
        // TODO: sobrescrever para processar somente um nó da busca.
    }

    isFinished() {
        return this.finished;
    }

    getPath() {
        return this.finalPath;
    }

    reconstructPath() {
        if (!this.found) {
            this.finalPath = [];
            return this.finalPath;
        }

        const path = [];
        let current = this.goal;

        while (current) {
            path.push(current);

            if (current === this.start) {
                break;
            }

            current = this.cameFrom.get(current);
        }

        if (path[path.length - 1] !== this.start) {
            this.finalPath = [];
            return this.finalPath;
        }

        this.finalPath = path.reverse();
        return this.finalPath;
    }

    finish(found) {
        this.finished = true;
        this.found = found;
        this.finalPath = found ? this.reconstructPath() : [];
    }

    reset() {
        this.frontier = [];
        this.visited = [];
        this.finalPath = [];
        this.finished = false;
        this.found = false;
        this.cameFrom = new Map();
    }
}


// ========================================
// src/search/PriorityQueue.js
// ========================================
class PriorityQueue {
    constructor() {
        this.items = [];
    }

    enqueue(element, priority) {
        const existingItem = this.items.find((item) => item.element === element);

        if (existingItem) {
            if (priority >= existingItem.priority) {
                return;
            }

            existingItem.priority = priority;
        } else {
            this.items.push({ element, priority });
        }

        this.items.sort((itemA, itemB) => itemA.priority - itemB.priority);
    }

    dequeue() {
        const item = this.items.shift();

        if (item) {
            return item.element;
        } else {
            return null;
        }
    }

    peek() {
        if (this.items.length > 0) {
            return this.items[0].element;
        } else {
            return null;
        }
    }

    isEmpty() {
        return this.items.length === 0;
    }

    size() {
        return this.items.length;
    }

    clear() {
        this.items = [];
    }

    contains(element) {
        return this.items.some((item) => item.element === element);
    }

    toArray() {
        return this.items.map((item) => item.element);
    }
}


// ========================================
// src/search/Heuristics.js
// ========================================
class Heuristics {
    static manhattan(cellA, cellB) {
        return Math.abs(cellA.col - cellB.col) + Math.abs(cellA.row - cellB.row);
    }
}


// ========================================
// src/search/BFS.js
// ========================================
class BFS extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.queue = [];
        this.discovered = new Set();

        this.init();
    }

    init() {
        if (this.start) {
            this.queue.push(this.start);
            this.frontier.push(this.start);
            this.discovered.add(this.start);
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.queue.length === 0) {
            this.finish(false);
            return;
        }

        const current = this.queue.shift();
        this.frontier = [...this.queue];
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            if (!this.discovered.has(neighbor)) {
                this.discovered.add(neighbor);
                this.cameFrom.set(neighbor, current);
                this.queue.push(neighbor);
                this.frontier.push(neighbor);
            }
        }
    }

    reset() {
        super.reset();
        this.queue = [];
        this.discovered = new Set();
        this.init();
    }
}


// ========================================
// src/search/DFS.js
// ========================================
class DFS extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.stack = [];
        this.discovered = new Set();

        this.init();
    }

    init() {
        if (this.start) {
            this.stack.push(this.start);
            this.frontier.push(this.start);
            this.discovered.add(this.start);
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.stack.length === 0) {
            this.finish(false);
            return;
        }

        // LIFO: o último nó empilhado é o próximo a ser processado.
        const current = this.stack.pop();
        this.frontier = [...this.stack];
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const neighbors = this.grid.getNeighbors(current);

        // Empilha em ordem reversa para que o primeiro vizinho de getNeighbors()
        // fique no topo da pilha e seja explorado primeiro.
        for (let i = neighbors.length - 1; i >= 0; i -= 1) {
            const neighbor = neighbors[i];

            if (!this.discovered.has(neighbor)) {
                this.discovered.add(neighbor);
                this.cameFrom.set(neighbor, current);
                this.stack.push(neighbor);
                this.frontier.push(neighbor);
            }
        }
    }

    reset() {
        super.reset();
        this.stack = [];
        this.discovered = new Set();
        this.init();
    }
}


// ========================================
// src/search/UniformCostSearch.js
// ========================================
class UniformCostSearch extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
        this.costSoFar = new Map();

        this.init();
    }

    init() {
        if (this.start) {
            // O custo inicial é zero: só cobramos a entrada nos vizinhos.
            this.costSoFar.set(this.start, 0);
            this.priorityQueue.enqueue(this.start, 0);
            this.frontier = this.priorityQueue.toArray();
        }
    }

    step() {
        if (this.finished) {
            return;
        }

        if (this.priorityQueue.isEmpty()) {
            this.finish(false);
            return;
        }

        const current = this.priorityQueue.dequeue();
        this.frontier = this.priorityQueue.toArray();
        this.visited.push(current);

        if (current === this.goal) {
            this.finish(true);
            return;
        }

        const currentCost = this.costSoFar.get(current);
        const neighbors = this.grid.getNeighbors(current);

        for (const neighbor of neighbors) {
            // Com custos não negativos, um nó expandido já tem custo mínimo.
            if (this.visited.includes(neighbor)) {
                continue;
            }

            const newCost = currentCost + neighbor.cost;
            const knownCost = this.costSoFar.get(neighbor);

            if (!this.costSoFar.has(neighbor) || newCost < knownCost) {
                this.costSoFar.set(neighbor, newCost);
                this.cameFrom.set(neighbor, current);
                this.priorityQueue.enqueue(neighbor, newCost);
            }
        }

        this.frontier = this.priorityQueue.toArray();
    }

    reset() {
        super.reset();
        this.priorityQueue.clear();
        this.costSoFar.clear();
        this.init();
    }
}


// ========================================
// src/search/GreedySearch.js
// ========================================
class GreedySearch extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
    }

    step() {
        // TODO: retirar somente o nó com menor heurística Manhattan.
        // TODO: adicionar vizinhos usando Heuristics.manhattan(vizinho, goal).
        // TODO: finalizar ao encontrar o objetivo ou esvaziar a fronteira.
    }
}


// ========================================
// src/search/AStar.js
// ========================================
class AStar extends SearchAlgorithm {
    constructor(grid, start, goal) {
        super(grid, start, goal);
        this.priorityQueue = new PriorityQueue();
        this.costSoFar = new Map();
    }

    step() {
        // TODO: retirar somente o nó com menor custo total estimado.
        // TODO: somar custo acumulado e Heuristics.manhattan(vizinho, goal).
        // TODO: atualizar fronteira, cameFrom e costSoFar quando houver melhora.
    }
}


// ========================================
// src/agent/Agent.js
// ========================================
class Agent {
    constructor(position) {
        this.position = position;
        this.path = [];
        this.currentPathIndex = 0;
        this.isMoving = false;
    }

    setPosition(cell) {
        this.position = cell;
    }

    setPath(path) {
        this.path = path;
        this.currentPathIndex = 0;
        this.isMoving = path.length > 1;
    }

    clearPath() {
        this.path = [];
        this.currentPathIndex = 0;
        this.isMoving = false;
    }

    getTerrainSpeedMultiplier() {
        if (!this.position) {
            return 0;
        }

        return Terrain.getSpeedMultiplier(this.position.terrainType);
    }

    update() {
        // TODO: avançar pelo caminho aos poucos, respeitando o tempo entre frames.
        // TODO: usar o multiplicador do terreno para definir a velocidade.
        // TODO: encerrar o movimento ao chegar à última célula do caminho.
    }

    display(cellSize) {
        if (!this.position) {
            return;
        }

        const centerX = this.position.col * cellSize + cellSize / 2;
        const centerY = this.position.row * cellSize + cellSize / 2;

        noStroke();
        fill(220, 50, 50);
        circle(centerX, centerY, cellSize * 0.55);
    }
}


// ========================================
// src/entities/Food.js
// ========================================
class Food {
    constructor(position) {
        this.position = position;
    }

    setPosition(cell) {
        this.position = cell;
    }

    relocate(grid) {
        // TODO: escolher uma célula transitável diferente da posição do agente.
    }

    display(cellSize) {
        if (!this.position) {
            return;
        }

        const centerX = this.position.col * cellSize + cellSize / 2;
        const centerY = this.position.row * cellSize + cellSize / 2;

        noStroke();
        fill(60, 170, 75);
        circle(centerX, centerY, cellSize * 0.4);
    }
}


// ========================================
// src/ui/UI.js
// ========================================
class UI {
    constructor() {
        this.availableAlgorithms = ["BFS", "DFS", "UCS", "GREEDY", "ASTAR"];
        this.selectedAlgorithm = "BFS";
    }

    initialize() {
        // TODO: criar o select de algoritmos.
        // TODO: criar os botões de iniciar e reiniciar.
        // TODO: criar o controle de velocidade da simulação.
    }

    setSelectedAlgorithm(name) {
        if (this.availableAlgorithms.includes(name)) {
            this.selectedAlgorithm = name;
            return true;
        }

        return false;
    }

    getSelectedAlgorithm() {
        return this.selectedAlgorithm;
    }

    update() {
        // TODO: ler as interações dos controles quando eles forem criados.
    }

    display() {
        // TODO: exibir informações e controles da simulação.
    }
}


// ========================================
// src/ui/SearchVisualizer.js
// ========================================
class SearchVisualizer {
    constructor(cellSize) {
        this.cellSize = cellSize;

        // Estado apenas visual: não altera a busca nem o ciclo da simulação.
        this.trackedSearch = null;
        this.pathFrames = 0;
    }

    display(search) {
        if (!search) {
            return;
        }

        this.updatePathAnimation(search);

        this.drawVisited(search.visited);
        this.drawFrontier(search.frontier);
        this.drawCurrent(search);
        this.drawPath(search.finalPath);
    }

    updatePathAnimation(search) {
        // Reinicia a animação quando uma nova busca começa ou a atual é reiniciada.
        if (search !== this.trackedSearch || search.finalPath.length === 0) {
            this.trackedSearch = search;
            this.pathFrames = 0;
        } else {
            this.pathFrames += 1;
        }
    }

    drawVisited(visited) {
        const colors = SearchVisualizer.COLORS;
        const trailLength = SearchVisualizer.TRAIL_LENGTH;
        const trailStart = visited.length - trailLength;

        push();
        noStroke();

        for (let i = 0; i < visited.length; i += 1) {
            // Os nós visitados mais recentemente ficam mais intensos,
            // formando um rastro que mostra o avanço da busca passo a passo.
            const recency = i >= trailStart ? (i - trailStart + 1) / trailLength : 0;
            const alpha = colors.visitedAlpha + (colors.trailAlpha - colors.visitedAlpha) * recency;

            fill(...colors.visited, alpha);
            this.drawCell(visited[i], 1);
        }

        pop();
    }

    drawFrontier(frontier) {
        const colors = SearchVisualizer.COLORS;

        push();
        stroke(...colors.frontierStroke);
        strokeWeight(2);
        fill(...colors.frontier);

        for (const cell of frontier) {
            this.drawCell(cell, this.cellSize * 0.25);
        }

        pop();
    }

    drawCurrent(search) {
        // O último nó visitado é o que acabou de ser expandido.
        if (search.isFinished() || search.visited.length === 0) {
            return;
        }

        const current = search.visited[search.visited.length - 1];

        push();
        noFill();
        stroke(...SearchVisualizer.COLORS.current);
        strokeWeight(3);
        this.drawCell(current, 2);
        pop();
    }

    drawPath(path) {
        if (!path || path.length === 0) {
            return;
        }

        const colors = SearchVisualizer.COLORS;
        const visibleCells = this.getVisiblePathLength(path);

        push();
        noFill();

        // O contorno escuro deixa o caminho legível sobre qualquer terreno.
        stroke(...colors.pathOutline);
        strokeWeight(this.cellSize * 0.3);
        this.drawPathSegments(path, visibleCells);

        stroke(...colors.path);
        strokeWeight(this.cellSize * 0.16);
        this.drawPathSegments(path, visibleCells);

        pop();
    }

    drawPathSegments(path, visibleCells) {
        if (visibleCells === 1) {
            const center = this.getCenter(path[0]);
            point(center.x, center.y);
            return;
        }

        for (let i = 1; i < visibleCells; i += 1) {
            const from = this.getCenter(path[i - 1]);
            const to = this.getCenter(path[i]);
            line(from.x, from.y, to.x, to.y);
        }
    }

    getVisiblePathLength(path) {
        // O caminho é revelado do início ao objetivo, uma célula a cada poucos quadros.
        const revealed = 1 + Math.floor(this.pathFrames / SearchVisualizer.PATH_FRAMES_PER_CELL);
        return Math.min(path.length, revealed);
    }

    getCenter(cell) {
        return {
            x: cell.col * this.cellSize + this.cellSize / 2,
            y: cell.row * this.cellSize + this.cellSize / 2
        };
    }

    drawCell(cell, inset) {
        rect(
            cell.col * this.cellSize + inset,
            cell.row * this.cellSize + inset,
            this.cellSize - inset * 2,
            this.cellSize - inset * 2
        );
    }
}

SearchVisualizer.TRAIL_LENGTH = 12;
SearchVisualizer.PATH_FRAMES_PER_CELL = 2;

SearchVisualizer.COLORS = Object.freeze({
    visited: Object.freeze([155, 89, 182]),
    visitedAlpha: 100,
    trailAlpha: 210,
    frontier: Object.freeze([255, 140, 0, 200]),
    frontierStroke: Object.freeze([150, 70, 0]),
    current: Object.freeze([255, 255, 255]),
    path: Object.freeze([255, 221, 0]),
    pathOutline: Object.freeze([40, 40, 40, 220])
});


// ========================================
// src/core/SimulationState.js
// ========================================
const SimulationState = Object.freeze({
    WAITING: "WAITING",
    SEARCHING: "SEARCHING",
    MOVING: "MOVING",
    COLLECTING: "COLLECTING"
});


// ========================================
// src/core/Simulation.js
// ========================================
class Simulation {
    constructor(options = {}) {
        const cols = options.cols || 20;
        const rows = options.rows || 15;
        const cellSize = options.cellSize || 40;

        this.grid = new Grid(cols, rows, cellSize);
        this.agent = new Agent(this.grid.getCell(0, 0));
        this.food = new Food(this.grid.getCell(cols - 1, rows - 1));
        this.ui = new UI();
        this.searchVisualizer = new SearchVisualizer(cellSize);
        this.search = null;
        this.score = 0;
        this.state = SimulationState.WAITING;

        this.ui.initialize();
    }

    update() {
        this.ui.update();

        if (this.state === SimulationState.WAITING) {
            this.updateWaiting();
        } else if (this.state === SimulationState.SEARCHING) {
            this.updateSearching();
        } else if (this.state === SimulationState.MOVING) {
            this.updateMoving();
        } else if (this.state === SimulationState.COLLECTING) {
            this.updateCollecting();
        }
    }

    updateWaiting() {
        // A simulação aguarda o usuário iniciar uma busca.
    }

    updateSearching() {
        if (!this.search || this.search.isFinished()) {
            return;
        }

        this.search.step();

        // TODO: quando a busca terminar, enviar o caminho ao agente e mudar o estado.
    }

    updateMoving() {
        this.agent.update();

        // TODO: mudar para COLLECTING quando o agente alcançar a comida.
    }

    updateCollecting() {
        // TODO: atualizar a pontuação, reposicionar a comida e voltar para WAITING.
    }

    startSearch() {
        const algorithmName = this.ui.getSelectedAlgorithm();

        this.search = this.createSearchAlgorithm(
            algorithmName,
            this.agent.position,
            this.food.position
        );

        this.setState(SimulationState.SEARCHING);
    }

    createSearchAlgorithm(algorithmName, start, goal) {
        if (algorithmName === "BFS") {
            return new BFS(this.grid, start, goal);
        }

        if (algorithmName === "DFS") {
            return new DFS(this.grid, start, goal);
        }

        if (algorithmName === "UCS") {
            return new UniformCostSearch(this.grid, start, goal);
        }

        if (algorithmName === "GREEDY") {
            return new GreedySearch(this.grid, start, goal);
        }

        if (algorithmName === "ASTAR") {
            return new AStar(this.grid, start, goal);
        }

        throw new Error(`Algoritmo desconhecido: ${algorithmName}`);
    }

    display() {
        this.grid.display();
        this.searchVisualizer.display(this.search);
        this.food.display(this.grid.cellSize);
        this.agent.display(this.grid.cellSize);
        this.ui.display();
    }

    setState(state) {
        if (!Object.values(SimulationState).includes(state)) {
            throw new Error(`Estado de simulação inválido: ${state}`);
        }

        this.state = state;
    }
}


// ========================================
// sketch.js
// ========================================
let simulation;

function setup() {
    createCanvas(800, 600);

    simulation = new Simulation({
        cols: 20,
        rows: 15,
        cellSize: 40
    });
}

function draw() {
    background(245);

    simulation.update();
    simulation.display();
}

