#!/bin/sh
set -eu

# Resolve paths from the repository so this script works from any directory.
cd "$(dirname "$0")/.."

sources="
src/world/Terrain.js
src/world/Cell.js
src/world/Grid.js
src/search/SearchAlgorithm.js
src/search/PriorityQueue.js
src/search/Heuristics.js
src/search/BFS.js
src/search/DFS.js
src/search/UniformCostSearch.js
src/search/GreedySearch.js
src/search/AStar.js
src/agent/Agent.js
src/entities/Food.js
src/ui/UI.js
src/ui/SearchVisualizer.js
src/core/SimulationState.js
src/core/Simulation.js
sketch.js
"

# Check every input before overwriting the emergency fallback.
for source in $sources style.css; do
    if [ ! -f "$source" ]; then
        printf 'Missing source file: %s\n' "$source" >&2
        exit 1
    fi
done

mkdir -p web-editor

{
    printf '// Generated by scripts/build-web-editor.sh. Edit src/ or root sketch.js, then regenerate.\n'

    for source in $sources; do
        printf '\n// ========================================\n// %s\n// ========================================\n' "$source"
        cat "$source"
        printf '\n'
    done
} > web-editor/sketch.js

# Keep the fallback styles in sync with the main page.
cp style.css web-editor/style.css

printf 'Generated web-editor/sketch.js and copied style.css.\n'
